# Version of docker-compose
version: "3"

services:
  app:
    build:
      context: . # Sets context to current directory
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: > # Defines the command for running project # Use "docker-command up" command to run this command
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment: # Set environment to match database service
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on: # Starts the services before starting app
      - db


  db:
    image: postgres:10-alpine # This image can be found in Docker Repository
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
